name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: sed -i '/fsevents/d' package-lock.json
      - run: npm install
      - run: npm test